  version: '3.4'

  services:
    backend:
      build:
        context: ./PokemonFuncAPI/AzureLabb3
        dockerfile: Dockerfile
      expose:
        - "8081:8081"
      environment:
        - ASPNETCORE_URLS=http://+:8081
        - ConnectionStrings__cosmosdb=mongodb://<your-cosmos-db-account>.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb

      networks:
        - app-network
      restart: on-failure

    frontend:
      build:
        context: ./Pokedex-ReactApp
        dockerfile: Dockerfile
      ports:
        - "80:80"
      environment:
        - NODE_ENV=production
        
      depends_on:
        - backend
      networks:
        - app-network
      restart: on-failure
        
  networks:
    app-network:
      
